---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections: 
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - CONVERKIT_SIGNUP_FORM=da21cefb3f
  - BUZZSPROUT_TOKEN=c87c35a37bc06dc59b1226472c694fa4
  - GOOGLE_ANALYTICS_ID=UA-45569809-2
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
